---
# Cisco Playbook:
# Create Vlans from Variable
# Add ports for variables to variable vlan


- name: Connection to Cisco devices
  hosts: platforms_ios
  gather_facts: false
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
  vars_files:
    - secrets.yml

  tasks:
    - name: Gather Facts
      cisco.ios.ios_facts:

    - name: Create Vlans from Variable
      cisco.ios.ios_vlans:
        config:
          - vlan_id: "{{ item }}"
            state: active
      loop: "{{ vlan_list }}"

    - name: Create Vlans from List of Dict
      cisco.ios.ios_vlans:
        config:
          - vlan_id: "{{ item.vlan_id }}"
            name: "{{ item.vlan_name }}"
            state: active
      loop: "{{ named_vlans }}"

    - name: Add ports for variables to variable vlan
      cisco.ios.l2_interfaces:
        config:
          - name: "{{ item.port_name }}"
            mode: access
            access:
              vlan: "{{ item.vlan_id }}"
      loop: "{{ vlan_ports }}"

    - name: Get Vlans
      cisco.ios.command:
        commands:
          - show vlan brief
      register: vlans

    - name: Debug Vlans
      ansible.builtin.debug:
        var: vars.vlans
      when: '"\n100 " in vars.vlans.stdout[0]'

    - name: Save Vlans to local file
      delegate_to: localhost
      ansible.builtin.copy:
        dest: cisco_vlans.txt
        content: "{{ vars.vlans.stdout[0] }}"

    - name: Gather facts for l2 interfaces
      cisco.ios.ios_l2_interfaces:
        config:
        state: gathered
      register: gathered_vlans
      
    - name: Save Vlans to local file
      delegate_to: localhost
      ansible.builtin.copy:
        dest: gathered_vlans_{{ ansible_host }}.txt
        content: "{{ vars.gathered_vlans }}"
